# Generated by Django 4.1.7 on 2023-08-14 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='kiosk',
            table='kiosks',
        ),
    ]
